-- TABELA: CLIENTES
-- Usada para identificar se o cliente já existe
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    nome TEXT,
    telefone TEXT UNIQUE -- Telefone deve ser único para evitar duplicatas
);

-- TABELA: CHATS
-- Usada para salvar o estado da conversa (ex: "inicio", "aguardando_valor")
CREATE TABLE IF NOT EXISTS public.chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    phone TEXT,
    estado_conversa TEXT DEFAULT 'inicio'
);

-- MEMÓRIA DO CHAT (LangChain / n8n)
-- Onde o histórico da conversa fica salvo
CREATE TABLE IF NOT EXISTS public.finanzas_n8n_chat_histories (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id TEXT NOT NULL,
    message JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- HABILITAR RLS (Row Level Security) - Opcional, mas recomendado
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finanzas_n8n_chat_histories ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS DE ACESSO (Permitir tudo para n8n com a chave de serviço)
create policy "Enable access to all users" on "public"."clientes"
as PERMISSIVE for ALL
to public
using (true)
with check (true);

create policy "Enable access to all users" on "public"."chats"
as PERMISSIVE for ALL
to public
using (true)
with check (true);

create policy "Enable access to all users" on "public"."finanzas_n8n_chat_histories"
as PERMISSIVE for ALL
to public
using (true)
with check (true);
